<ClientesScreen>:
    MDBoxLayout:
        orientation: "vertical"
        
        MDTopAppBar:
            title: "Clientes"
            elevation: 10
            left_action_items: [["arrow-left", lambda x: root.go_back()]]
            
        MDScrollView:
            MDList:
                id: clientes_list
                
        MDFloatingActionButton:
            icon: "plus"
            pos_hint: {"center_x": 0.9, "center_y": 0.1}
            on_release: root.show_add_dialog()